### ISSUE TITLE
Unable to screenshare entire screen anywhere with underscan enabled in NVIDIA X server settings.

### ISSUE THREAD

**Issue by IvanHuylo** [pop-os/nvidia-graphics-drivers#110]
I use underscan because my monitor is a bit old and has no built-in function of underscan, so i have to use the nvidia feature either on windows or linux. When i turn off the underscan then everything is fine, once i turn it on when i stay too long on screen choosing menu from discord screen share then it crashes with this:

```
Unexpected crash report id length
Failed to get crash dump id.
Report Id: 
Segmentation fault (core dumped)
```

Also, with enabled underscan the picture is all messed up. A screenshot: https://imgur.com/9NG809M
Funny thing is that messed up place in the bottom, i cant see it on screen and my cursor is not able to touch this place, but discord sees this place. I can screenshare applications only because they dont catch this place as said, the cursor doesnt go there, but discord sees that place somehow, and OBS too.

Im using PopOS cosmics with 465.31 drivers. Back then, a few months ago, this didn't happen with older driver version like 435 and it doesn't happen on windows.
Should i try downgrading, or is there some sort of a fix?
Tell me if i need to provide more specific information.
Disabling h264 in discord helps a bit, but i think it is a driver issue, since on 435 and older versions everything was fine.

**Comment by bflanagin** [comment]
Thanks for reaching out, unfortunately we try to keep support requests to a minimum so that bugs and other issues are easier to sort at solve. However, it's possible there is a bug in the 465 driver that causes the issue. I would check to see which driver you're using on the Windows side of things and try to match the version numbers a closely as possible. Which may require a downgrade to 460 or 435. If you need help with that and holding the package so it doesn't automatically update when we push a new nvidia-driver package you can get support over  at https://chat.pop-os.org
